# Generated by Django 2.0.1 on 2018-03-15 08:19

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180315_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='s', upload_to=posts.models.upload_location),
            preserve_default=False,
        ),
    ]
