# Generated by Django 2.0.1 on 2018-03-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
